### 클래스

In [5]:
class Cookie:
    pass

a = Cookie()

print(type(a))

<class '__main__.Cookie'>

In [ ]:
class FourCal:
    # 클래스에서 함수를 사용할 때는 반드시 self 매개변수 사용
    # self -> 실행 시점점의 함수를 포함하는 객체 자신을 가르키는 변수
    def __init__(self, first, second): # 변수 초기화
        self.first = first
        self.second = second
    
    def add(self): # 함수
        return self.first + self.second
    def sub(self):
        return self.first - self.second
    def mul(self):
        return self.first * self.second
    def div(self):
        return self.first / self.second

In [ ]:
cal1 = FourCal() # 객체 생성 => 프로그램에서 사용가능한 상태(메모리에 변수와 함수가 올라가는 상태)

cal1.setData(10,30)

print(cal1.add(),cal1.sub(),cal1.mul(),cal1.div())

### 클래스의 상속

In [15]:
# 클래스의 상속 : 새로운 클래스를 생성
# 기존의 클래스의 맴버(변수, 메서드)들을 받아서 새로운 클래스 생성
# 오버라이딩 : 메서드를 수정(처리블록)해서 사용
# MoreFourlCal : 새로운 클래스 정의 -> pow 제곱 구해주는 함수, div 메서드를 수정
class MoreFourCal(FourCal):
    def pow(self):
        return self.first ** self.second
    
    #  오버라이딩: 함수의 이름과 매개변수는 그대로 하고 처리부붑ㄴ을 수정해서 정의
    def div(self):
        if self.second == 0 :
            return 0
        return self.first/self.second

In [18]:
mfc1 = MoreFourCal(10,3)
print(mfc1.add())  # 13
print(mfc1.pow())  # 1000

mfc1.div()

13
1000

3.3333333333333335

### 모듈

In [5]:
import mod2

print(mod2.PI) # PI 라는 변수를 사용하겠다

a = mod2.Math() # mod의 Math라는 클래스를 사용한다
print(a.solv(2))

print(mod2.add(mod2.PI, 4.4))

3.141592
12.566368
7.5415920000000005

### 외부 모듈

### 표준 라이브러리

In [ ]:
# datetime
import datetime

day1 = datetime.date(2026, 1, 25)
day2 = datetime.date(2026, 1, 1)

print(day1 - day2)
print(day1.year, day1.month, day1.day)

24 days, 0:00:00
2026 1 25

In [ ]:
# time
import time
time.time()

1773032345.1993992

In [17]:
time.localtime()

time.struct_time(tm_year=2026, tm_mon=3, tm_mday=9, tm_hour=13, tm_min=59, tm_sec=9, tm_wday=0, tm_yday=68, tm_isdst=0)

In [ ]:
import random as r
r.random() # 0 이상 1 미만의 실수를 반환

0.6180694142944473

In [32]:
int(r.random()*10)

1

In [41]:
r.randint(1, 46) # 특정 범위의 무작위 수를 반환

4

In [ ]:
list_score = []
for s in range(0,9): # 몇번 반복? 1~9번
    list_score.append(r.randint(60,100)) # 반복할 때마다 60에서 100사이에 숫자를 하나 리스트에 추가함.
print(list_score)

[65, 99, 85, 68, 79, 92, 86, 80, 78]

In [ ]:
r.choice(list_score) # 무작위 하나를 추출

78

In [ ]:
r.sample(list_score, 3) # 샘플로 3개롤 무작위 추출

[79, 65, 78]

In [63]:
import json

# 읽으려는 json 파일은 문자열 "str" 이다.
with open('data.json', 'r', encoding='utf8') as f :
    # str -> dict
    data = json.load(f)

print(data)
print(data, type(data))

{'name': 'COOL', 'age': 25}
{'name': 'COOL', 'age': 25} <class 'dict'>

### 넘파이

In [64]:
import pandas as pd
print(pd.__version__)

import numpy as np
print(np.__version__)

3.0.1
2.4.2

In [65]:
# ndarray : 넘파이 배열 생성
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>

In [ ]:
arr + 10

array([11, 12, 13, 14, 15])

In [68]:
# 배열 생성
# 각 요소의 값을 0으로 채워서 생성
# 배열의 사이즈를 설정
# 사이즈의 정의 : 2차원 형식으로 행과, 열을 정의해서 생성
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]

In [69]:
# 1로 채운 배열
ones = np.ones((5,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

In [70]:
# 일련번호로 생성
# 0~10 사이의 숫자를 2칸씩 간격으로 생성
seq1 = np.arange(0, 11, 2)
print(seq1)

[ 0  2  4  6  8 10]

In [73]:
# 지정된 범위 안에서 동일한 간격으로 숫자를 생성
# 시작, 끝, 몇개
# 1~10, 4
linspace = np.linspace(1, 10, 5)
print(linspace)

[ 1.    3.25  5.5   7.75 10.  ]

In [78]:
# 배열의 속성 확인
list_temp = [[1,2,3],[4,5,6]]

arr1 = np.array(list_temp)
print(arr1)
print(arr1.shape) # 배열의 사이즈 : (행, 열) -> (2,3)
print(arr1.ndim) # 배열의 차원 : 2
print(arr1.size) # 배열의 요소 개수 : 6
print(arr1.dtype) # 요소의 타입 : int64

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64

In [80]:
# 배열의 인덱싱 : list와 동일
arr = np.array([10,20,30,40])
print(arr[0])
print(arr[-1])

10
40

In [83]:
print(arr1)
print(arr1[0], type(arr1[0]))
print(arr1[1][2])

[[1 2 3]
 [4 5 6]]
[1 2 3] <class 'numpy.ndarray'>
6

In [ ]:
arr = np.array([10,20,30,40,50])
# 슬라이싱
print(arr[:]) # 처음부터 끝까지
print(arr[1:])  # 인덱스 1부터 끝까지
print(arr[1:3]) # 인덱스 1 부터 인덱스 3까지
print(arr[2:9]) # 인덱스 2부터  인덱스 9까지 (인덱스 4까지 있지만 초과해도 끝까지 출력)

[10 20 30 40 50]
[20 30 40 50]
[20 30]
[30 40 50]

In [ ]:
arr = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(arr)
print(arr[:2,1:]) #

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]

In [92]:
# 배열의 연산 : +, *, **
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 + 10)
print(arr1 + arr2)
print(arr1 * arr2)
print(arr2**2)

[11 12 13]
[5 7 9]
[ 4 10 18]
[16 25 36]

In [1]:
# 배열의 구조 변환 : 1-> 2, 2 -> 1
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr.shape)

(6,)

In [ ]:
# 2차원 -> 1차원
flated_arr = reshaped_arr.f

In [2]:
# 필터링
arr = np.array([1,2,3,4,5,6])
filtered_arr = arr[arr>3]
print(filtered_arr)

[4 5 6]

In [32]:
# 7. 난수 생성해서 배열을 생성
ran_arr1 = np.random.rand(10)
print(ran_arr1)

ran_arr2 = np.random.randint(1, 10, size=(5,3)) # 5행 3열
print(ran_arr2)

[0.83490909 0.53452587 0.95437141 0.16720101 0.31030275 0.89117756
 0.7787056  0.4253061  0.93543089 0.67548148]
[[3 7 6]
 [6 7 4]
 [9 5 6]
 [6 1 2]
 [4 4 7]]

### 판다스

In [35]:
import pandas as pd

# DataFrame 생성 : 2차원 형식의 표 모양으로 데이터 구조 생성
# dict -> 'key' : [ ] 
# key-> 열 이름, [ ] 각 행의 데이터들
data = {
    'name':['cool','hot','king'],
    'age':[20, 30, 25]
}
df = pd.DataFrame(data)
print(df, type(df))
df

   name  age
0  cool   20
1   hot   30
2  king   25 <class 'pandas.DataFrame'>

   name  age
0  cool   20
1   hot   30
2  king   25

In [36]:
df.head()

   name  age
0  cool   20
1   hot   30
2  king   25

In [37]:
df.tail()

   name  age
0  cool   20
1   hot   30
2  king   25

In [39]:
# 데이터 구조 확인
df.shape # 구조 확인 (3행 2열)

(3, 2)

In [40]:
# 데이터의 요약 정보
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [41]:
# 기초 통계 지표( 숫자 )
df.describe()

        age
count   3.0
mean   25.0
std     5.0
min    20.0
25%    22.5
50%    25.0
75%    27.5
max    30.0

In [49]:
# 합, 평균
print(df['age'])
print(df['age'] < 30)
print(df[df['age'] < 30])
print(df['age'].sum())

0    20
1    30
2    25
Name: age, dtype: int64
0     True
1    False
2     True
Name: age, dtype: bool
   name  age
0  cool   20
2  king   25
75

In [50]:
data = {
    'name':['cool','hot','king'],
    'age':[20, 30, 25],
    'score':[90, 70, 60]
}
df = pd.DataFrame(data)
df

   name  age  score
0  cool   20     90
1   hot   30     70
2  king   25     60

In [51]:
df[['name', 'score']]

   name  score
0  cool     90
1   hot     70
2  king     60

In [62]:
data = {
    'name':['SON'],
    'age':[29],
    'score':[99],
    'passed': [True]
}
df2 = pd.DataFrame(data)
df2

  name  age  score  passed
0  SON   29     99    True

In [63]:
df['passed'] = df['score'] >= 70
df

   name  age  score  passed
0  cool   20     85    True
1   hot   30     70    True
2  king   25     60   False

In [64]:
df3 = pd.concat([df,df2], ignore_index=True)
print(df3)

   name  age  score  passed
0  cool   20     85    True
1   hot   30     70    True
2  king   25     60   False
3   SON   29     99    True

In [65]:
# 특정 위치의 값을 변경
df.loc[0, 'score'] = 85
df

   name  age  score  passed
0  cool   20     85    True
1   hot   30     70    True
2  king   25     60   False

In [66]:
df3.loc[0, 'score'] = 85
df3

   name  age  score  passed
0  cool   20     85    True
1   hot   30     70    True
2  king   25     60   False
3   SON   29     99    True

In [ ]:
df3.info()
df3.describe() # NaN 은 카운팅하지 않음

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   score   4 non-null      int64
 3   passed  4 non-null      bool
dtypes: bool(1), int64(2), str(1)
memory usage: 232.0 bytes

             age      score
count   4.000000   4.000000
mean   26.000000  78.500000
std     4.546061  17.097758
min    20.000000  60.000000
25%    23.750000  67.500000
50%    27.000000  77.500000
75%    29.250000  88.500000
max    30.000000  99.000000

In [ ]:
df3.isnull() # NaN 여부 판단 (NaN일 경우 True)

    name    age  score  passed
0  False  False  False   False
1  False  False  False   False
2  False  False  False   False
3  False  False  False   False

In [73]:
# 결측치에 기본값을 저장
df3['score'] = df3['score'].fillna(100)
df3

   name  age  score  passed
0  cool   20     85    True
1   hot   30     70    True
2  king   25     60   False
3   SON   29     99    True

In [ ]:
df3.loc[1, 'score'] = None # 결측값 삽입
df3

   name  age  score  passed
0  cool   20   85.0    True
1   hot   30    NaN    True
2  king   25   60.0   False
3   SON   29   99.0    True

In [ ]:
# 결측치의 행을 삭제
df3 = df3.dropna()
df3

   name  age  score  passed
0  cool   20   85.0    True
2  king   25   60.0   False
3   SON   29   99.0    True

In [79]:
# 정렬
sorted_df = df3.sort_values(by='score', ascending=False) # 가장 높은 점수로 정렬됨.
top_2 = sorted_df.head(2)
top_2

   name  age  score  passed
3   SON   29   99.0    True
0  cool   20   85.0    True

In [80]:
# 그룹핑 : ~ 별 -> groupby()
data = {
    'team':['A', 'A', 'B', 'B', 'A'],
    'score':[80, 90, 88, 72, 95]
}
df = pd.DataFrame(data)
df

  team  score
0    A     80
1    A     90
2    B     88
3    B     72
4    A     95

In [82]:
grouped_data = df.groupby('team')['score'].sum()
grouped_data

team
A    265
B    160
Name: score, dtype: int64

In [87]:
grouped_data = df.groupby('team')['score'].mean()
grouped_data

team
A    88.333333
B    80.000000
Name: score, dtype: float64

In [ ]:
df.to_csv('output.csv', index=False) # 파일 저장 (csv로 파일 저장 / 인덱스를 제외)

In [93]:
data_csv = pd.read_csv('output.csv')
print(data_csv)
print(type(data_csv))

  team  score
0    A    180
1    A    190
2    B    188
3    B    172
4    A    195
<class 'pandas.DataFrame'>